# Generated by Django 5.0.1 on 2024-01-15 16:23

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=15)),
                ('Surname', models.CharField(max_length=15)),
                ('Othername', models.CharField(max_length=15)),
                ('Gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], default='male', max_length=15)),
                ('Religion', models.CharField(choices=[('CHRISTIAN', 'christian'), ('MUSLIM', 'muslim'), ('OTHERS', 'others')], default='christian', max_length=15)),
                ('Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Whatsapp_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Seed', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')])),
                ('Address', models.TextField()),
                ('Hobbies', models.TextField()),
                ('Ref_id', models.IntegerField(default=0)),
            ],
        ),
    ]
